eshop2/eshop2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/',include('products.urls')),
    path('accounts/', include('registration.backends.default.urls')),          
    path('',RedirectView.as_view(url="products/")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop2/products/urls.py
from django.urls.conf import path
from django.views.generic.base import RedirectView
from products import views
urlpatterns = [
    path('cart/addquantity/<int:pk>',views.additemquantity),
    path('cart/removequantity/<int:pk>',views.removeitemquantity),
    path('cart/add/<int:pk>',views.cart),
    path('deliver/',views.deliverview),
    path('cart/',views.CartView.as_view()),
    path('contact/',views.ContactView.as_view()),
    path('about/',views.AboutView.as_view()),
    path('recents/<int:pk>',views.recentsView),
    path('sold/',views.OrderedView.as_view()),
    path('cart/remove/<int:pk>',views.cartdel),
    path('product_list/',views.ProductListView.as_view()),
    path('product_list/<int:pk>/',views.ProductDetailView.as_view()),
    path('profile/edit/<int:pk>/',views.ProfileEditView.as_view(success_url="/products/product_list")),
    path('',RedirectView.as_view(url="product_list/")),
]

eshop2/products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.utils.datetime_safe import datetime
from datetime import timedelta
from django.core.validators import RegexValidator

# Create your models here.
class Product(models.Model):
    p_name = models.CharField(max_length=100)
    p_price = models.FloatField()
    p_date = models.DateTimeField(auto_now_add=True)
    p_des = models.TextField()
    p_img = models.ImageField(upload_to="images")
    p_instock = models.IntegerField(default=1)
    def __str__(self):
        return "%s (%s)" % (self.p_name, self.p_date)

class Profile(models.Model):
    user = models.OneToOneField(to=User, on_delete=CASCADE)
    name = models.CharField(max_length=100)
    profile_pic = models.ImageField(upload_to="images",null=True)
    gender = models.CharField(max_length=100,choices=(('male','male'),('female','female'),('others','others')))
    phone = models.CharField(validators=[RegexValidator("^0?[5-9]{1}\d{9}$")],max_length=15)
    hno = models.CharField(max_length=100)  
    street = models.CharField(max_length=100)
    landmark = models.CharField(max_length=100)
    pincode = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    dist = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    user_register_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return "%s (%s)" % (self.user, self.name)
    
class Sold(models.Model):
    user = models.ForeignKey(to=User,on_delete=CASCADE)
    p_name = models.CharField(max_length=100)
    p_price = models.FloatField()
    p_img = models.ImageField(upload_to="images")
    p_quantity = models.IntegerField(null=True,default=1)
    amount = models.FloatField(null=True,blank=True)
    p_instock = models.IntegerField(default=1)
    sold_on = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '%s' %(self.p_name)
    
class Deliver(models.Model):
    products = models.ManyToManyField(Sold)
    name = models.ForeignKey(to=User,on_delete=CASCADE)
    cust_name = models.CharField(max_length=100)
    phone = models.CharField(validators=[RegexValidator("^0?[5-9]{1}\d{9}$")],max_length=15)
    hno = models.CharField(max_length=100)  
    street = models.CharField(max_length=100)
    landmark = models.CharField(max_length=100)
    pincode = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    dist = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    sold_on = models.DateTimeField(auto_now_add=True)  
    delivered_on = models.DateTimeField(auto_now_add=True,null=True)
    def __str__(self):
        return '%s' %(self.name)


class Cart(models.Model):
    product = models.CharField(max_length=100)
    p_name = models.CharField(max_length=100)
    p_price = models.FloatField()
    p_img = models.ImageField(upload_to="images")
    p_quantity = models.IntegerField(null=True,default=1)
    amount = models.FloatField(default=0)
    p_instock = models.IntegerField(default=1)
    def __str__(self):
        return "%s (%s)" % (self.product, self.p_name)
    

    

eshop2/products/views.py
from django.shortcuts import render
from products.models import Product, Profile, Cart, Sold, Deliver
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect
from django.views.generic.base import TemplateView
from django.db.models import Q

# Create your views here.
@method_decorator(login_required,name="dispatch")
class ProductListView(ListView):
    model = Product
    def get_queryset(self):
        si = self.request.GET.get('si')
        if si==None:
            si=" "
        products = Product.objects.filter(Q(p_name__icontains=si)|Q(p_price__icontains=si)|Q(p_des__icontains=si))
        for p1 in products:
            p1.ordered = False
            ob = Cart.objects.filter(product = p1,p_name = p1.p_name,p_price=p1.p_price)
            if ob:
                p1.ordered = True
        return products
        
            
@method_decorator(login_required, name="dispatch")
class ProductDetailView(DetailView):
    model = Product
    
class AboutView(TemplateView):
    template_name = "products/about.html"
    
class ContactView(TemplateView):
    template_name = "products/contact.html"
    
    
@method_decorator(login_required, name="dispatch")
class ProfileEditView(UpdateView):
    model = Profile
    fields = ['name','profile_pic','gender','phone','hno','street','landmark','city','pincode','dist','state']
    template_name="products/profile_form.html"
    
@method_decorator(login_required, name="dispatch")
class CartView(ListView):
    model = Cart
    template_name="products/cart_form.html"
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        amounts = Cart.objects.all()
        total_amount = 0
        for a in amounts:
            Cart.objects.filter(product=a.product,p_name=a.p_name,p_price=a.p_price,p_quantity=a.p_quantity,p_img=a.p_img).update(amount = a.p_price * a.p_quantity)
        total_amounts = Cart.objects.all()
        for ta in total_amounts:
            total_amount += ta.amount
        data['no_of_items'] = total_amounts.count()
        data['total_amount'] = total_amount
        return data

@method_decorator(login_required, name="dispatch")
class OrderedView(ListView):
    template_name ="products/sold_form.html"
    def get_queryset(self):
        ordereditems = Cart.objects.all()
        for items in ordereditems:
            Sold.objects.create(user=self.request.user,p_name=items.p_name,p_price=items.p_price,p_img=items.p_img,amount=items.amount,p_quantity=items.p_quantity,p_instock=items.p_instock)
            Product.objects.filter(p_name=items.p_name).update(p_instock = items.p_instock - items.p_quantity) 
            Cart.objects.filter(p_name=items.p_name,p_price=items.p_price,p_img=items.p_img,amount=items.amount,p_quantity=items.p_quantity,p_instock=items.p_instock).delete()
              
            
        return HttpResponseRedirect(redirect_to="products/sold_form.html")
    
def recentsView(req,pk):
    profile = Profile.objects.get(pk=pk)
    recents = Deliver.objects.filter(name=profile.user).order_by("-id")
    
    lst1 = []
    for r in recents:
        rp = r.products.all()
        for ob in rp:
            ls = []
            lst = []
            img = ob.p_img
            ls.append(img)
            name = ob.p_name
            ls.append(name)
            price = ob.p_price
            ls.append(price)
            quantity = ob.p_quantity
            ls.append(quantity)
            amount = ob.amount
            ls.append(amount)
            delivered_on = ob.sold_on
            ls.append(delivered_on)
            lst.append(ls)
            lst1.append(lst)
        break
    lst2 = lst1           
    return render(req,"products/recents.html",{'lst' : lst2})      
def deliverview(req):
    items_to_sold = Sold.objects.filter(user=req.user)
    d1 = Deliver(name=req.user,cust_name=req.user.profile.name,phone=req.user.profile.phone,hno=req.user.profile.hno,street=req.user.profile.street,landmark=req.user.profile.landmark,city=req.user.profile.city,pincode=req.user.profile.pincode,dist=req.user.profile.pincode,state=req.user.profile.state)
    d1.save()
    for ci in items_to_sold:
       d1.products.add(ci)
    d1.save()
        
    
    return render(req,"products/confirm.html")
         
def cart(req,pk):
    product = Product.objects.get(pk=pk)
    Cart.objects.create(product=product,p_name=product.p_name,p_price=product.p_price,p_img=product.p_img,p_instock=product.p_instock)
    
    return HttpResponseRedirect(redirect_to = "/products/product_list")

def cartdel(req,pk):
    product = Product.objects.get(pk=pk)
    Cart.objects.filter(product=product,p_name=product.p_name,p_price=product.p_price,p_img=product.p_img).delete()
    return HttpResponseRedirect(redirect_to ="/products/product_list")    

def additemquantity(req,pk):
    item = Cart.objects.get(pk=pk)
    Cart.objects.filter(pk=item.pk).update(p_quantity=item.p_quantity+1)
    return HttpResponseRedirect(redirect_to="/products/cart")

def removeitemquantity(req,pk):
    item = Cart.objects.get(pk=pk)
    Cart.objects.filter(pk=item.pk).update(p_quantity=item.p_quantity-1)
    return HttpResponseRedirect(redirect_to="/products/cart")

eshop2/templates/products/Contact.html
{% extends 'base.html' %}
{% block title %}Contact{% endblock %}
{% block content %}
 {% load static %}
   <link rel="stylesheet" type = "text/css" href="{% static "css/contact.css" %}">
<section id="contact-form">
  <h2>Contact Us</h2>
  <form id="contact" name="contact" accept-charset="utf-8">
    <label><span>Name</span><input name="name" type="text" placeholder="Name"/></label>
    <label><span>Email</span><input name="email" type="email" placeholder="Email"/></label>
    <label><span>Message</span><textarea name="message" placeholder="Message"></textarea></label>
    <input name="submit" type="submit" value="Send"/>
  </form>
</section>
{% endblock %}

eshop2/templates/products/about.html
{% extends 'base.html' %}
{% block title %}about{% endblock %}
{% block content %}
  <div class="container">
        <h1 class="text-center text-info">About Us</h1>
        <div class="text-info">
<p style="text-align:justify">
E-commerce (electronic commerce) is the activity of electronically buying or selling of products on online services or over the Internet. Electronic commerce draws on technologies such as mobile commerce, electronic funds transfer, supply chain management, Internet marketing, online transaction processing, electronic data interchange (EDI), inventory management systems, and automated data collection systems. E-commerce is in turn driven by the technological advances of the semiconductor industry, and is the largest sector of the electronics industry.
</p style="text-align:justify">
<p>
Modern electronic commerce typically uses the World Wide Web for at least one part of the transaction's life cycle although it may also use other technologies such as e-mail. Typical e-commerce transactions include the purchase of online books (such as Amazon) and music purchases (music download in the form of digital distribution such as iTunes Store), and to a less extent, customized/personalized online liquor store inventory services.[1] There are three areas of e-commerce: online retailing, electronic markets, and online auctions. E-commerce is supported by electronic business.[2]
</p>

 </div>
  </div>
{% endblock %}

eshop2/templates/products/cart_form.html
{% extends 'base.html' %}
{% block title %}cart{% endblock %}
{% block content %}
<div class="container-sm">
  <div class="container-sm alert alert-primary">
      <table class="table table-responsive">
    <thead >
      <tr>
        <th>Product</th>
        <th>Name</th>
        <th>Quantity</th>
        <th>Price</th>
         <th>Amount</th>
      </tr>
    </thead>
    <tbody >
      {% for p in cart_list %}
      <tr>
        <td><img src="/media/{{p.p_img}}" height=80px width=80px class="img-fluid rounded"></td>
        <td>{{p.p_name}}</td>
        <td>{{p.p_quantity}}</td>
        <td><span class="text-dark" style="font-size:20px;">&#8377;</span>{{p.p_price}}</td>
        <td><span class="text-dark" style="font-size:20px;">&#8377;</span>{{p.amount}}</td>
        {% if p.p_quantity < p.p_instock %}
        <td><a class="btn btn-primary" href="/products/cart/addquantity/{{p.id}}">+</a></td>
        {% endif %}
       {% if p.p_quantity > 1 %}
        <td><a class="btn btn-danger" href="/products/cart/removequantity/{{p.id}}">-</a></td>
        {% endif %}

      </tr>
       {% endfor %}
    </tbody>
    </table>
   </div>
    <h4 class="text-center"> Total Amount is </h4><h5 class="text-primary text-center"><span class="text-dark" style="font-size:30px;">&#8377;</span> {{total_amount}}</h5>
    {% if total_amount == 0%}
       <h5 class="text-danger text-center">Your Cart is empty</h5>
    {%else%}
    <a class="btn btn-success" style="float:right;" href="/products/sold">Place Order</a>
    {% endif %}
    <a class="btn btn-dark" style="float:left;" href="/products/product_list">Back</a>  
   <br>
<br>
  <hr>
     <div class="alert alert-success">
    <h3>Deliver Address :</h3>
     <p>To:{{user.profile.name}}</p>
     <p>DNO:{{user.profile.hno}}</p>
     <p>{{user.profile.street}}</p>
     <p>{{user.profile.landmark}}</p>
     <p>{{user.profile.city}}</p>
     <p>pincode:{{user.profile.pincode}}</p>
     <p>{{user.profile.dist}}(dist)</p>
     <p>{{user.profile.state}}</p>
     </div>
    
     
      
</div>
</div>
</div>
{% endblock %}

eshop2/templates/products/confirm.html
{% extends 'base.html' %}
{% block title %}Order{% endblock %}
{% block content %}
  <div class="container jumbotron">
    <div class="row">
      <ul>
      <h3 class="text-success text-center">Your Order is Successful !!!!!</h3>
      <h5 class="text-primary text-center">Your order will deliver with in 5 - 10 working days</h5>
      <h5 class="alert alert-danger text-center">Cash On Delivery [COD]</h5>
      </ul>
     </div>
      <br>
      <hr>
      <h4 class="text-success text-center"> Thank You !! </h4>
      <br>
  </div>
{% endblock %}

eshop2/templates/products/product_detail.html
{% extends 'base.html' %}
{% block title %}Detail{% endblock %}
{% block content %}
<br> 
<div class="container">
            <div class="row">
                <div class="col-sm-6">
                   <img src="/media/{{product.p_img}}" class="img-fluid" height="450px" width="450px" alt="nodisplay">
                 </div>
             <div class="col-sm-6">
                 <h5 class="text-primary">{{product.p_name}}<h5>
                  <h5 class="alert alert-success"><span class="text-dark" style="font-size:30px;">&#8377;</span>.{{product.p_price}}</h5>
                  <h5 class="text-info">Description : </h5>
                   <p>{{product.p_des}}</p>
                  <h5 class="text-danger">Stock Available : <h5 class="alert alert-danger">{{product.p_instock}}</h5></h5>
                 <a class="btn btn-dark" href="/products/product_list">Back</a>
             </div> 
             </div>
            </div>
{% endblock %}

eshop2/templates/products/product_list.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="container">
        <nav class="navbar">
            <ul class="navbar-nav ml-auto">             
                   <form class="form-inline my-2 my-lg-0">
                     <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="si" value="{{ request.GET.si }}">
                     <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                     </form>
           </ul>
</nav>
<hr>
            <div class="row">
              {% for p in product_list %}
                <div class="col-md-6 col-lg-4 my-2">
                    <div class="card h-100" style="width: 18rem;" >
                        <img src="/media/{{p.p_img}}" class="card-img-top img-fluid" >
                        <div class="card-body">
                            <h5 class="card-title">{{p.p_name | truncatechars:20}}</h5>
                            <h5 class="card-text"><span class="text-dark" style="font-size:30px;">&#8377;</span>{{p.p_price}}</h5>
                            <a href="/products/product_list/{{p.id}}" class="btn btn-primary">View Details</a>
                            <br><br>
                            {% if p.ordered == True %} 
                            <a href="/products/cart/remove/{{p.id}}" class="btn btn-light">Remove</a>
                            {% else %}
                            {% if p.p_instock != 0 %}
                            <a href="/products/cart/add/{{p.id}}" class="btn btn-success">Add to Cart</a>
                            {% else %} 
                            <p class="text-danger">Out of Stock!!!!</p>
                            {% endif %}
                           {% endif %} 
                       </div>
                    </div>

                </div>
              {% endfor %}
</div>
</div>
{% endblock %}

eshop2/templates/products/profile_form.html
{% extends 'base.html' %}
{% block title %}profile{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
<div class="row">
<div class="col-md-6">
<img src="/media/{{profile.profile_pic}}" width="350px" height="350px" class="img-fluid rounded-circle">
</div>
<div class="col-md-6 jumbotron">
<h1>My Profile</h1>
<p style="color:green;font-weight=3">Your Account was Created on {{user.profile.user_register_date}}</p>
<form method="post" enctype="multipart/form-data"">
{% csrf_token %}
{{ form|crispy }}
{% csrf_token %}
<br>
<input type="submit" class="btn btn-success"value="Submit"/>
</form>
</div>
</div>
</div>
{% endblock %}

eshop2/templates/products/recents.html
{% extends 'base.html' %}
{% block title %}Order{% endblock %}
{% block content %}
  <div class="container jumbotron">
    <div class="row">
<h3>Your Orders</h3>
     <table class="table table-responsive">
    <thead>
      <th>
        Product
      </th>
       <th>
        Product Name
      </th>
       <th>
        Price
      </th>
       <th>
        Quantity
      </th>
      <th>
        Amount
      </th>
      <th>
        Deliverd_on
      </th>
     </thead>
       {% for l in lst %}
       <tr>  
           {% for x in l %}
             <td><img src="/media/{{x.0}}" width=80px height=80px/></td>
             <td>{{x.1}}</td>
             <td><span class="text-dark" style="font-size:20px;">&#8377;</span>{{x.2}}</td>
             <td>{{x.3}}</td>
             <td><span class="text-dark" style="font-size:20px;">&#8377;</span>{{x.4}}</td>
             <td>{{x.5}}</td>
           {% endfor %}
       <tr>
        {% endfor %}
    </table>
    
  </div>
{% endblock %}








{{name}}
    {{img}}
    {{price}}
    {{quantity}}
    {{amount}}
    {{sold_on}}

eshop2/templates/products/sold_form.html
{% extends 'base.html' %}
{% block title %}Order{% endblock %}
{% block content %}
  <div class="container">
     <h2>Please Confirm Your Order </h2>
       <a class="btn btn-success my-3" href="/products/deliver">Confirm Order</a>
   
  </div>
{% endblock %}